export const INDIAN_STATES = [
  {
    name: "Andhra Pradesh",
    cities: [
      "Amaravati",
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Tirupati",
      "Kurnool",
      "Nellore",
      "Anantapur",
      "Rajahmundry",
      "Kadapa",
      "Ongole",
      "Eluru",
    ],
  },
  {
    name: "Arunachal Pradesh",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Tawang",
      "Pasighat",
      "Ziro",
      "Bomdila",
      "Tezu",
      "Namsai",
      "Roing",
      "Aalo",
    ],
  },
  {
    name: "Assam",
    cities: [
      "Dispur",
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Tinsukia",
      "Nagaon",
      "Tezpur",
      "Bongaigaon",
      "Karimganj",
    ],
  },
  {
    name: "Bihar",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Ara",
      "Begusarai",
      "Munger",
      "Katihar",
    ],
  },
  {
    name: "Chhattisgarh",
    cities: [
      "Raipur",
      "Bilaspur",
      "Durg",
      "Bhilai",
      "Korba",
      "Raigarh",
      "Jagdalpur",
      "Rajnandgaon",
      "Ambikapur",
      "Dhamtari",
    ],
  },
  {
    name: "Goa",
    cities: [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Curchorem",
      "Canacona",
      "Quepem",
      "Valpoi",
    ],
  },
  {
    name: "Gujarat",
    cities: [
      "Gandhinagar",
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Anand",
      "Mehsana",
      "Nadiad",
      "Morbi",
    ],
  },
  {
    name: "Haryana",
    cities: [
      "Chandigarh",
      "Gurugram",
      "Faridabad",
      "Hisar",
      "Panipat",
      "Karnal",
      "Rohtak",
      "Sonipat",
      "Ambala",
      "Yamunanagar",
    ],
  },
  {
    name: "Himachal Pradesh",
    cities: [
      "Shimla",
      "Dharamshala",
      "Solan",
      "Mandi",
      "Kullu",
      "Bilaspur",
      "Hamirpur",
      "Chamba",
      "Nahan",
      "Una",
    ],
  },
  {
    name: "Jammu and Kashmir",
    cities: [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Udhampur",
      "Kathua",
      "Pulwama",
      "Kupwara",
      "Kulgam",
      "Sopore",
    ],
  },
  {
    name: "Jharkhand",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Hazaribagh",
      "Deoghar",
      "Giridih",
      "Ramgarh",
      "Medininagar",
      "Chaibasa",
    ],
  },
  {
    name: "Karnataka",
    cities: [
      "Bengaluru",
      "Mysuru",
      "Hubballi",
      "Dharwad",
      "Mangaluru",
      "Belagavi",
      "Kalaburagi",
      "Ballari",
      "Shivamogga",
      "Tumakuru",
      "Davangere",
      "Udupi",
    ],
  },
  {
    name: "Kerala",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Thrissur",
      "Kollam",
      "Alappuzha",
      "Kannur",
      "Palakkad",
      "Malappuram",
      "Kottayam",
      "Ernakulam",
      "Idukki",
    ],
  },
  {
    name: "Madhya Pradesh",
    cities: [
      "Bhopal",
      "Indore",
      "Gwalior",
      "Jabalpur",
      "Ujjain",
      "Sagar",
      "Satna",
      "Ratlam",
      "Rewa",
      "Khandwa",
      "Chhindwara",
      "Hoshangabad",
    ],
  },
  {
    name: "Maharashtra",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Thane",
      "Aurangabad",
      "Solapur",
      "Kolhapur",
      "Amravati",
      "Jalgaon",
      "Ahmednagar",
      "Sangli",
    ],
  },
  {
    name: "Manipur",
    cities: [
      "Imphal",
      "Thoubal",
      "Churachandpur",
      "Ukhrul",
      "Bishnupur",
      "Senapati",
      "Tamenglong",
      "Jiribam",
      "Kakching",
      "Moreh",
    ],
  },
  {
    name: "Meghalaya",
    cities: [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongpoh",
      "Baghmara",
      "Williamnagar",
      "Mairang",
      "Resubelpara",
      "Sohra",
      "Mawkyrwat",
    ],
  },
  {
    name: "Mizoram",
    cities: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Serchhip",
      "Kolasib",
      "Mamit",
      "Saiha",
      "Lawngtlai",
      "Siaha",
      "Hnahthial",
    ],
  },
  {
    name: "Nagaland",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Mon",
      "Phek",
      "Longleng",
      "Kiphire",
    ],
  },
  {
    name: "Odisha",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Balasore",
      "Baripada",
      "Jharsuguda",
      "Puri",
      "Jeypore",
      "Angul",
      "Bargarh",
    ],
  },
  {
    name: "Punjab",
    cities: [
      "Chandigarh",
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Hoshiarpur",
      "Firozpur",
      "Pathankot",
      "Moga",
      "Sangrur",
    ],
  },
  {
    name: "Rajasthan",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Kota",
      "Ajmer",
      "Bikaner",
      "Alwar",
      "Bhilwara",
      "Sikar",
      "Pali",
      "Tonk",
      "Barmer",
      "Jaisalmer",
    ],
  },
  {
    name: "Sikkim",
    cities: [
      "Gangtok",
      "Namchi",
      "Gyalshing",
      "Mangan",
      "Singtam",
      "Rangpo",
      "Pakshyong",
      "Soreng",
      "Ravangla",
      "Jorethang",
    ],
  },
  {
    name: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Erode",
      "Vellore",
      "Thoothukudi",
      "Dindigul",
      "Thanjavur",
      "Kanchipuram",
      "Nagercoil",
    ],
  },
  {
    name: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Khammam",
      "Mahbubnagar",
      "Nalgonda",
      "Adilabad",
      "Suryapet",
      "Siddipet",
      "Ramagundam",
      "Mancherial",
    ],
  },
  {
    name: "Tripura",
    cities: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Ambassa",
      "Belonia",
      "Kailashahar",
      "Khowai",
      "Sonamura",
      "Kamalpur",
      "Bishalgarh",
    ],
  },
  {
    name: "Uttar Pradesh",
    cities: [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Noida",
      "Agra",
      "Varanasi",
      "Prayagraj",
      "Meerut",
      "Bareilly",
      "Aligarh",
      "Moradabad",
      "Saharanpur",
      "Gorakhpur",
      "Jhansi",
      "Mathura",
    ],
  },
  {
    name: "Uttarakhand",
    cities: [
      "Dehradun",
      "Haridwar",
      "Rishikesh",
      "Haldwani",
      "Roorkee",
      "Kashipur",
      "Rudrapur",
      "Pithoragarh",
      "Nainital",
      "Almora",
      "Tehri",
      "Bageshwar",
    ],
  },
  {
    name: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Malda",
      "Kharagpur",
      "Burdwan",
      "Jalpaiguri",
      "Haldia",
      "Cooch Behar",
      "Darjeeling",
    ],
  },
];

export const STATE_OPTIONS = INDIAN_STATES.map((entry) => entry.name);

export const getCitiesForState = (stateName) => {
  if (!stateName) {
    return [];
  }
  const entry = INDIAN_STATES.find((state) => state.name === stateName);
  return entry ? entry.cities : [];
};
